Support for valgrind when running unit-test. The code was adapted from gstreamer Makefile.
git-svn-id: file:///home/yoann/SVN/libprelude/trunk@10874 09c5ec92-17d4-0310-903a-819935f44dba

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -6,4 +6,40 @@ AM_CPPFLAGS = -I$(top_builddir)/src/include -I$(top_srcdir)/src/include -I$(top_
 idmef_value_LDADD = $(top_builddir)/src/idmef-value.lo $(LDADD)
 
 check-local:
+	$(MAKE) valgrind
 	cd $(top_srcdir)/libmissing/tests && $(MAKE) check
+
+
+if HAVE_VALGRIND
+
+%.valgrind: %
+	libtool --mode=execute                                  \
+	$(VALGRIND) -q                                          \
+	--tool=memcheck --leak-check=full --trace-children=yes  \
+	--leak-resolution=high --num-callers=20                 \
+	$* 2>&1 | tee valgrind.log				
+	@if grep "==" valgrind.log > /dev/null 2>&1; then       \
+		rm valgrind.log;                                \
+		exit 1;                                         \
+	fi
+	@rm valgrind.log
+
+valgrind: $(TESTS)
+	@echo "Valgrinding tests ..."
+	@failed=0;                                                      \
+	for t in $(TESTS); do   					\
+		$(MAKE) $$t.valgrind;                                   \
+		if test "$$?" -ne 0; then                               \
+			echo "Valgrind error for test $$t";             \
+			failed=`expr $$failed + 1`;                     \
+			whicht="$$whicht $$t";                          \
+		fi;                                                     \
+	done;                                                           \
+	if test "$$failed" -ne 0; then                                  \
+		echo "$$failed tests had leaks or errors under valgrind:";      \
+		echo "$$whicht";                                        \
+		false;                                                  \
+	fi
+else
+valgrind:
+endif
